InhaBas/Inhabas.com-api

- .gitignore
- build.gradle
- src/main/java/com/inhabas/api/ApiApplication.java
- src/main/java/com/inhabas/api/controller/BoardController.java
- src/main/java/com/inhabas/api/controller/MemberController.java
- src/main/java/com/inhabas/api/domain/board/Board.java
- src/main/java/com/inhabas/api/domain/board/Category.java
- src/main/java/com/inhabas/api/domain/member/IbasInformation.java
- src/main/java/com/inhabas/api/domain/member/Major.java
- src/main/java/com/inhabas/api/domain/member/Member.java
- src/main/java/com/inhabas/api/domain/member/Role.java
- src/main/java/com/inhabas/api/domain/member/SchoolInformation.java
- src/main/java/com/inhabas/api/dto/BoardDto.java
- src/main/java/com/inhabas/api/repository/board/BoardRepository.java
- src/main/java/com/inhabas/api/repository/board/MemoryBoardRepository.java
- src/main/java/com/inhabas/api/repository/member/JpaMemberRepository.java
- src/main/java/com/inhabas/api/repository/member/MemberRepository.java
- src/main/java/com/inhabas/api/service/member/MemberService.java
- src/main/java/com/inhabas/api/service/member/MemberServiceImpl.java
- src/test/java/com/inhabas/api/board/repository/MemoryBoardRepositoryTest.java
- src/test/java/com/inhabas/api/member/MemberServiceTest.java
validation 및 jwt 토큰 등은 아직 신경 안쓰고 
간단한 기능 구현에만 초점을 맞췄음.
> [feature/member] 멤버 도메인, 레파지토리, 서비스, 컨트롤러 구현

- build.gradle
- src/main/java/com/inhabas/api/config/QuerydslConfiguration.java
- gradlew compileQuerydsl 명령어를 통해서 Q 클래스 빌드해야함.
> [feature] Querydsl 적용.

- .github/workflows/deploy-dev.yml
- .github/workflows/gradle-build.yml
- .gitignore
- build.gradle
- src/main/java/com/inhabas/api/ApiApplication.java
- src/main/java/com/inhabas/api/config/CloudConfig.java
- src/main/java/com/inhabas/api/domain/menu/Menu.java
- src/main/resources/bootstrap.yml
* [feature] slack notification
* [feature] spring cloud config 적용 
* [config] spring cloud config 버전 명세
* [feature] github action 배포파일 작성 (deploy-dev.yml)
> [feature/cicd] 슬랙 알림 및 배포 설정 (#42)

- build.gradle
- src/main/java/com/inhabas/api/controller/LoginController.java
- src/main/java/com/inhabas/api/security/AuthenticateEndPointUrlProperties.java
- src/main/java/com/inhabas/api/security/WebSecurityConfig.java
- src/main/java/com/inhabas/api/security/WebSecurityConfig_dev.java
- src/main/java/com/inhabas/api/security/domain/AuthUser.java
- src/main/java/com/inhabas/api/security/domain/AuthUserNotFoundException.java
- src/main/java/com/inhabas/api/security/domain/AuthUserRepository.java
- src/main/java/com/inhabas/api/security/domain/AuthUserService.java
- src/main/java/com/inhabas/api/security/domain/RefreshToken.java
- src/main/java/com/inhabas/api/security/domain/RefreshTokenRepository.java
- src/main/java/com/inhabas/api/security/domain/RefreshTokenService.java
- src/main/java/com/inhabas/api/security/jwtUtils/InvalidJwtTokenException.java
- src/main/java/com/inhabas/api/security/jwtUtils/InvalidJwtTokenHandler.java
- src/main/java/com/inhabas/api/security/jwtUtils/JwtAuthenticationProcessingFilter.java
- src/main/java/com/inhabas/api/security/jwtUtils/JwtAuthenticationToken.java
- src/main/java/com/inhabas/api/security/jwtUtils/JwtTokenDecodedInfo.java
- src/main/java/com/inhabas/api/security/jwtUtils/JwtTokenProvider.java
- src/main/java/com/inhabas/api/security/jwtUtils/TokenDecodedInfo.java
- src/main/java/com/inhabas/api/security/jwtUtils/TokenDto.java
- src/main/java/com/inhabas/api/security/jwtUtils/TokenProvider.java
- src/main/java/com/inhabas/api/security/oauth2/CustomAuthenticationFailureHandler.java
- src/main/java/com/inhabas/api/security/oauth2/CustomAuthenticationSuccessHandler.java
- src/main/java/com/inhabas/api/security/oauth2/CustomOAuth2User.java
- src/main/java/com/inhabas/api/security/oauth2/CustomOAuth2UserService.java
- src/main/java/com/inhabas/api/security/oauth2/OAuth2Config.java
- src/test/java/com/inhabas/api/ApiApplicationTests.java
- src/test/java/com/inhabas/security/jwt/JwtTokenProviderTest.java
- src/test/resources/application.yml
*[feature] OAuth2 인증 기능
- AuthUser 생성
- CustomOAuth2UserService 구현
- HttpSessionAuthorizedClientRepository 사용
- success, failure 핸들러 등록
*[feature] TokenProvider 생성
- jwt 신규발급, 재발급, 검증 및 디코딩 기능
- refresh 토큰은 entity 로 생성 => db 에 저장
*[feature] JwtAuthenticationProcessingFilter 등록
- api 요청 올 때, request 헤더에서 jwt 토큰 검사
*[config] spring security 개발 환경분리
- dev 환경은 프론트에서 작업해야하기 때문에, cors 풀었음.
**resolve** : #3
**also see** : #58
> [feature] 회원 인증 시스템 ( OAuth2, Jwt )

- src/main/java/com/inhabas/api/controller/MenuController.java
- src/main/java/com/inhabas/api/domain/menu/Menu.java
- src/main/java/com/inhabas/api/domain/menu/MenuGroup.java
- src/main/java/com/inhabas/api/domain/menu/MenuRepository.java
- src/main/java/com/inhabas/api/domain/menu/MenuRepositoryCustom.java
- src/main/java/com/inhabas/api/domain/menu/MenuRepositoryImpl.java
- src/main/java/com/inhabas/api/domain/menu/MenuType.java
- src/main/java/com/inhabas/api/dto/menu/MenuDto.java
- src/main/java/com/inhabas/api/dto/menu/MenuGroupDto.java
- src/main/java/com/inhabas/api/security/WebSecurityConfig.java
- src/main/java/com/inhabas/api/security/WebSecurityConfig_dev.java
- src/main/java/com/inhabas/api/service/menu/MenuNotExistException.java
- src/main/java/com/inhabas/api/service/menu/MenuService.java
- src/main/java/com/inhabas/api/service/menu/MenuServiceImpl.java
- src/test/java/com/inhabas/api/domain/MenuRepositoryTest.java
- src/test/java/com/inhabas/api/service/MenuServiceTest.java
- src/test/resources/application.yml
- `/menu/all` 모든 메뉴 정보 불러옴
- `/menu?menuId=%d` 해당 메뉴 정보 불러옴
resolve: #66
> [feature] 메뉴 정보 불러오는 api 생성

- src/main/java/com/inhabas/api/controller/MenuController.java
- src/main/java/com/inhabas/api/domain/menu/Menu.java
- src/main/java/com/inhabas/api/domain/menu/MenuGroup.java
- src/main/java/com/inhabas/api/domain/menu/MenuRepository.java
- src/main/java/com/inhabas/api/domain/menu/MenuRepositoryCustom.java
- src/main/java/com/inhabas/api/domain/menu/MenuRepositoryImpl.java
- src/main/java/com/inhabas/api/domain/menu/MenuType.java
- src/main/java/com/inhabas/api/dto/menu/MenuDto.java
- src/main/java/com/inhabas/api/dto/menu/MenuGroupDto.java
- src/main/java/com/inhabas/api/security/WebSecurityConfig.java
- src/main/java/com/inhabas/api/security/WebSecurityConfig_dev.java
- src/main/java/com/inhabas/api/service/menu/MenuNotExistException.java
- src/main/java/com/inhabas/api/service/menu/MenuService.java
- src/main/java/com/inhabas/api/service/menu/MenuServiceImpl.java
- src/test/java/com/inhabas/api/domain/MenuRepositoryTest.java
- src/test/java/com/inhabas/api/service/MenuServiceTest.java
- src/test/resources/application.yml
- `/menu/all` 모든 메뉴 정보 불러옴
- `/menu?menuId=%d` 해당 메뉴 정보 불러옴
resolve: #66
> [feature/menuInfo] 메뉴 정보 불러오는 api 생성

- src/main/java/com/inhabas/api/domain/contest/ContestBoard.java
> [Feature/#73] ContestBoard Entity에 DiscriminatorValue 추가

- src/main/java/com/inhabas/api/controller/BoardController.java
- src/main/java/com/inhabas/api/controller/ContestBoardController.java
- src/main/java/com/inhabas/api/domain/board/BoardNotFoundException.java
- src/main/java/com/inhabas/api/domain/board/NormalBoard.java
- src/main/java/com/inhabas/api/domain/contest/ContestBoard.java
- src/main/java/com/inhabas/api/dto/board/SaveBoardDto.java
- src/main/java/com/inhabas/api/dto/contest/SaveContestBoardDto.java
- src/main/java/com/inhabas/api/security/WebSecurityConfig_dev.java
- src/main/java/com/inhabas/api/security/argumentResolver/AuthUserArgumentResolver.java
- src/main/java/com/inhabas/api/security/domain/AuthUserDetail.java
- src/main/java/com/inhabas/api/service/board/BoardService.java
- src/main/java/com/inhabas/api/service/board/BoardServiceImpl.java
- src/main/java/com/inhabas/api/service/contest/ContestBoardService.java
- src/main/java/com/inhabas/api/service/contest/ContestBoardServiceImpl.java
- src/test/java/com/inhabas/api/controller/BoardControllerTest.java
- src/test/java/com/inhabas/api/controller/ContestBoardControllerTest.java
- src/test/java/com/inhabas/api/dto/board/SaveBoardDtoTest.java
- src/test/java/com/inhabas/api/dto/contest/SaveContestBoardDtoTest.java
- src/test/java/com/inhabas/api/service/BoardServiceTest.java
- src/test/java/com/inhabas/api/service/ContestBoardServiceTest.java
- src/test/java/com/inhabas/security/argumentResolver/ArgumentResolverTest.java
- src/test/resources/application.yml
- Controller에서 Integer Id를 받으면 토큰이 주어지도록 설정 + 테스트 케이스 추가
- ResponseEntity 반환하도록 설정
- Swagger API 문서화
- 게시판 URL 설정
see: #80
> [refactor/#79] 게시판 코드 리팩토링

- .github/workflows/gradle-build.yml
- src/main/java/com/inhabas/api/service/login/HttpOriginProviderForDevelopment.java
- src/main/java/com/inhabas/api/service/login/HttpOriginProviderForProduction.java
- src/main/java/com/inhabas/api/service/login/LoginRedirectHeaderHeaderProvider.java
- src/main/java/com/inhabas/api/service/login/LoginRedirectHeaderParamProvider.java
- src/main/java/com/inhabas/api/service/login/LoginRedirectHeaderProvider.java
- src/main/java/com/inhabas/api/service/login/LoginService.java
- src/main/java/com/inhabas/api/service/login/LoginServiceImpl.java
- src/test/java/com/inhabas/api/controller/LoginControllerTest.java
- src/test/java/com/inhabas/api/dto/contest/SaveContestBoardDtoTest.java
- src/test/java/com/inhabas/api/dto/contest/UpdateContestBoardDtoTest.java
- src/test/java/com/inhabas/api/service/LoginRedirectHeaderProviderTest.java
- src/test/java/com/inhabas/api/service/LoginServiceTest.java
- src/test/resources/application.yml
@MingyeomKim 공모전 테스트 코드 문제가 있어서 리팩토링 했습니다~ 참고해주세요~
> [refactor/signUp] 토큰을 파라미터에 넣는 걸로 변경

- auth-module/src/main/java/com/inhabas/api/auth/AuthSecurityConfig.java
- auth-module/src/main/java/com/inhabas/api/auth/domain/oauth2/CustomOAuth2UserService.java
- auth-module/src/main/java/com/inhabas/api/auth/domain/oauth2/userInfo/OAuth2UserInfoAuthentication.java
- auth-module/src/main/java/com/inhabas/api/auth/domain/token/jwtUtils/JwtAuthenticationResult.java
- auth-module/src/main/java/com/inhabas/api/auth/domain/token/jwtUtils/JwtTokenProvider.java
- auth-module/src/main/java/com/inhabas/api/auth/domain/token/securityFilter/UserPrincipalService.java
- auth-module/src/test/java/com/inhabas/api/auth/domain/token/JwtTokenProviderTest.java
- auth-module/src/test/java/com/inhabas/api/auth/utils/argumentResolver/ArgumentResolverTest.java
- resource-server/src/main/java/com/inhabas/api/domain/member/MemberRepositoryCustom.java
- resource-server/src/main/java/com/inhabas/api/domain/member/MemberRepositoryImpl.java
- resource-server/src/main/java/com/inhabas/api/domain/member/security/MemberAuthorityProvider.java
- resource-server/src/main/java/com/inhabas/api/domain/member/security/MemberPrincipalService.java
- resource-server/src/main/java/com/inhabas/api/domain/member/security/socialAccount/MemberSocialAccount.java
- resource-server/src/main/java/com/inhabas/api/domain/member/security/socialAccount/MemberSocialAccountRepository.java
- resource-server/src/main/java/com/inhabas/api/domain/member/security/socialAccount/MemberSocialAccountRepositoryCustom.java
- resource-server/src/main/java/com/inhabas/api/domain/member/security/socialAccount/MemberSocialAccountRepositoryImpl.java
- resource-server/src/test/java/com/inhabas/annotataion/WithMockJwtAuthenticationTokenSecurityContextFactory.java
- resource-server/src/test/java/com/inhabas/api/domain/MemberRepositoryTest.java
- resource-server/src/test/java/com/inhabas/api/domain/MemberSocialAccountRepositoryTest.java
- resource-server/src/test/java/com/inhabas/api/domain/member/security/MemberAuthorityProviderTest.java
- resource-server/src/test/java/com/inhabas/api/domain/member/security/MemberPrincipalServiceTest.java
- resource-server/src/test/java/com/inhabas/api/service/BoardServiceTest.java
- resolve: [Inhabas.com/#102](https://github.com/InhaBas/Inhabas.com/issues/102)
- also see : #95
> [feature/Inhabas#102] 소셜로그인 호환성 작업

- auth-module/src/main/java/com/inhabas/api/auth/domain/oauth2/handler/Oauth2AuthenticationFailureHandler.java
- auth-module/src/main/java/com/inhabas/api/auth/domain/oauth2/handler/Oauth2AuthenticationSuccessHandler.java
- auth-module/src/test/java/com/inhabas/api/auth/domain/oauth2/handler/Oauth2AuthenticationFailureHandlerTest.java
- auth-module/src/test/java/com/inhabas/api/auth/domain/oauth2/handler/Oauth2AuthenticationSuccessHandlerTest.java
- build.gradle
> [bugfix/#122] OAuth2 인증 실패 시에도, redirect_url 검사하도록 수정

- resource-server/src/main/java/com/inhabas/api/domain/menu/MenuId.java
- resource-server/src/main/java/com/inhabas/api/dto/menu/MenuDto.java
- resource-server/src/main/java/com/inhabas/api/dto/menu/MenuGroupDto.java
- resource-server/src/test/java/com/inhabas/api/controller/MenuControllerTest.java
> [bugfix/#126] 메뉴 dto에서 id 안보이는 문제 해결

- auth-module/src/main/java/com/inhabas/api/auth/domain/exception/AuthExceptionCodes.java
- auth-module/src/main/java/com/inhabas/api/auth/domain/exception/BadRequestException.java
- auth-module/src/main/java/com/inhabas/api/auth/domain/exception/UserNotFoundException.java
- resource-server/src/main/java/com/inhabas/api/domain/member/security/MemberAuthorityProvider.java
- resource-server/src/test/java/com/inhabas/api/domain/member/security/MemberAuthorityProviderTest.java
> [bugfix/#128] 가입되지 않은 회원이 로그인하면 UserNotFoundException 을 발생

- resource-server/src/main/java/com/inhabas/api/config/WebConfig.java
- resource-server/src/test/java/com/inhabas/api/web/configTest/WebConfigTest.java
- resource-server/src/test/java/com/inhabas/testConfig/TestEmptyController.java
> [invalid/#145] swagger ui 에서 snake_case 로 표기되도록 변경

- resource-server/src/main/java/com/inhabas/api/domain/board/BaseBoard.java
- resource-server/src/main/java/com/inhabas/api/domain/board/BoardCannotModifiableException.java
- resource-server/src/main/java/com/inhabas/api/domain/board/domain/NormalBoard.java
- resource-server/src/main/java/com/inhabas/api/domain/board/dto/BoardDto.java
- resource-server/src/main/java/com/inhabas/api/domain/board/repository/NormalBoardRepositoryImpl.java
- resource-server/src/main/java/com/inhabas/api/domain/board/usecase/BoardService.java
- resource-server/src/main/java/com/inhabas/api/domain/board/usecase/BoardServiceImpl.java
- resource-server/src/main/java/com/inhabas/api/domain/contest/domain/ContestBoard.java
- resource-server/src/main/java/com/inhabas/api/domain/contest/usecase/ContestBoardService.java
- resource-server/src/main/java/com/inhabas/api/domain/contest/usecase/ContestBoardServiceImpl.java
- resource-server/src/main/java/com/inhabas/api/domain/menu/domain/valueObject/MenuId.java
- resource-server/src/main/java/com/inhabas/api/web/BoardController.java
- resource-server/src/main/java/com/inhabas/api/web/ContestBoardController.java
- resource-server/src/test/java/com/inhabas/api/domain/BaseEntityTest.java
- resource-server/src/test/java/com/inhabas/api/domain/board/domain/NormalBoardTest.java
- resource-server/src/test/java/com/inhabas/api/domain/board/repository/NormalBoardRepositoryTest.java
- resource-server/src/test/java/com/inhabas/api/domain/board/usecase/BoardServiceTest.java
- resource-server/src/test/java/com/inhabas/api/domain/contestBoard/usecase/ContestBoardServiceTest.java
- resource-server/src/test/java/com/inhabas/api/web/BoardControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/ContestBoardControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/MenuControllerTest.java
- 작성자만 변경가능하도록 변경
- json 응답 필드 평탄화 (`@JsonUnwrapped`)
- 페이지네이션 디폴트 개수 설정 
resolve #135
> [refactor/#135] 게시글 CRUD 리팩토링

- .github/workflows/deploy-dev.yml
- resource-server/src/main/java/com/inhabas/api/web/BoardController.java
- resource-server/src/main/java/com/inhabas/api/web/BudgetApplicationController.java
- resource-server/src/main/java/com/inhabas/api/web/BudgetHistoryController.java
- resource-server/src/main/java/com/inhabas/api/web/CommentController.java
- resource-server/src/main/java/com/inhabas/api/web/ContestBoardController.java
- resource-server/src/main/java/com/inhabas/api/web/MemberController.java
- resource-server/src/main/java/com/inhabas/api/web/MenuController.java
- resource-server/src/main/java/com/inhabas/api/web/SignUpController.java
- resource-server/src/main/java/com/inhabas/api/web/TeamController.java
- resource-server/src/test/java/com/inhabas/api/securityConfig/RoleHierarchyTest.java
- resource-server/src/test/java/com/inhabas/api/web/BoardControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/BudgetApplicationControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/BudgetHistoryControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/CommentControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/ContestBoardControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/MemberControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/MenuControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/SignUpControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/TeamControllerTest.java
> [refactor/#137] restful 하게 api 변경

- .github/workflows/deploy-dev.yml
- resource-server/src/main/java/com/inhabas/api/config/WebSecurityConfig.java
- resource-server/src/main/java/com/inhabas/api/web/BoardController.java
- resource-server/src/test/java/com/inhabas/api/web/BoardControllerTest.java
> [invalid] 바뀐 api 에 맞게 security filter 수정.

- resource-server/src/main/java/com/inhabas/api/domain/comment/domain/Comment.java
- resource-server/src/main/java/com/inhabas/api/domain/comment/dto/CommentDetailDto.java
- resource-server/src/main/java/com/inhabas/api/domain/comment/dto/CommentSaveDto.java
- resource-server/src/main/java/com/inhabas/api/domain/comment/dto/CommentUpdateDto.java
- resource-server/src/main/java/com/inhabas/api/domain/comment/repository/CommentRepositoryImpl.java
- resource-server/src/main/java/com/inhabas/api/domain/comment/usecase/CommentService.java
- resource-server/src/main/java/com/inhabas/api/domain/comment/usecase/CommentServiceImpl.java
- resource-server/src/main/java/com/inhabas/api/domain/member/domain/valueObject/MemberId.java
- resource-server/src/main/java/com/inhabas/api/web/BoardController.java
- resource-server/src/main/java/com/inhabas/api/web/CommentController.java
- resource-server/src/test/java/com/inhabas/api/domain/comment/repository/CommentRepositoryTest.java
- resource-server/src/test/java/com/inhabas/api/domain/comment/usecase/CommentServiceTest.java
- resource-server/src/test/java/com/inhabas/api/securityConfig/RoleHierarchyTest.java
- resource-server/src/test/java/com/inhabas/api/web/BoardControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/CommentControllerTest.java
예전에 작성해 놓은 코드인데,
토큰에서 현재 사용자 정보 resolve 한 뒤에 처리하도록 수정하기
> [bugfix/#151] 댓글 CRUD 수정

- build.gradle
- resource-server/src/main/java/com/inhabas/api/config/sshTunneling/SshApplicationListener.java
- resource-server/src/main/java/com/inhabas/api/config/sshTunneling/SshConfig.java
- resource-server/src/main/java/com/inhabas/api/web/argumentResolver/ArgumentResolverConfig.java
- resource-server/src/main/java/com/inhabas/api/web/interceptor/InterceptorConfig.java
- resource-server/src/test/java/com/inhabas/testConfig/InterceptorConfigMockBean.java
- resource-server/src/test/java/com/inhabas/testConfig/TestConfigurationForSecurity.java
개발 db를 aws 로 옮겼음.
database 와 직접 연결되는 것을 피하고 연결을 암호화하고자
ssh tunneling 사용
> [feature/#149] 로컬 개발용 ssh tunneling 적용

- resource-server/src/main/java/com/inhabas/api/config/WebSecurityConfig.java
- resource-server/src/main/java/com/inhabas/api/domain/lecture/repository/StudentRepository.java
- resource-server/src/main/java/com/inhabas/api/domain/lecture/repository/StudentRepositoryCustom.java
- resource-server/src/main/java/com/inhabas/api/domain/lecture/repository/StudentRepositoryImpl.java
- resource-server/src/main/java/com/inhabas/api/domain/lecture/usecase/LectureStudentService.java
- resource-server/src/main/java/com/inhabas/api/domain/lecture/usecase/LectureStudentServiceImpl.java
- resource-server/src/main/java/com/inhabas/api/web/LectureController.java
- resource-server/src/test/java/com/inhabas/api/domain/lecture/repository/StudentRepositoryTest.java
- resource-server/src/test/java/com/inhabas/api/domain/lecture/usecase/LectureStudentServiceMockTest.java
- resource-server/src/test/java/com/inhabas/api/domain/member/domain/MemberTest.java
- resource-server/src/test/java/com/inhabas/api/web/LectureControllerTest.java
수강생 정보 조회 로직 빼먹었음.
상태변경 로직에서 `강의id` 를 무조건 참고하도록 변경함.
> [feature] 수강생 정보 조회 로직 추가 

- resource-server/src/main/java/com/inhabas/api/config/WebConfig.java
- resource-server/src/main/java/com/inhabas/api/domain/menu/domain/valueObject/MenuId.java
- resource-server/src/test/java/com/inhabas/api/web/BudgetApplicationControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/BudgetHistoryControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/CommentControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/LectureControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/MenuControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/configTest/WebConfigTest.java
- resource-server/src/test/resources/application.yml
> Revert "[Refactor/#168] JSON Property Case 변경 (SNAKE_CASE -> LOWER_CAMEL_CASE)"

- resource-server/src/main/java/com/inhabas/api/config/WebConfig.java
- resource-server/src/main/java/com/inhabas/api/domain/menu/domain/valueObject/MenuId.java
- resource-server/src/test/java/com/inhabas/api/web/BudgetApplicationControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/BudgetHistoryControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/CommentControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/LectureControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/MenuControllerTest.java
- resource-server/src/test/java/com/inhabas/api/web/configTest/WebConfigTest.java
- resource-server/src/test/resources/application.yml
Reverts InhaBas/Inhabas.com-api#170
기존 SNAKE_CASE로 설계된 JSON Property의 설정과 JSON 변수들을 전부 LOWER_CAMEL_CASE에 맞게 변경하였습니다.
주요 변경사항
com.inhabas.api > resource-server > main > config > WebConfig 의 PropertyNamingStrategies를 LOWER_CAMEL_CASE로 변경
com.inhabas.api > resource-server > test > resources > application.yml 의 PropertyNamingStrategies를 LOWER_CAMEL_CASE로 변경
두 변경사항과 관련된 모든 테스트 파일들의 JSON 변수의 이름을 SNAKE_CASE > LOWER_CAMEL_CASE로 변경
모든 테스트 통과, 빌드 이상없음.
> [Refactor/#168] JSON Property Case 변경 (SNAKE_CASE -> LOWER_CAMEL_CASE)

- resource-server/src/test/resources/application.yml
> [refactor] application.yml 오타 수정

- module-auth/src/main/java/com/inhabas/api/auth/domain/oauth2/member/domain/entity/UpdateNameRequest.java
- module-auth/src/test/java/com/inhabas/api/auth/domain/oauth2/member/repository/UpdateNameRequestRepositoryTest.java
UPDATE_NAME_REQUEST table columnDefinition 수정 및 Repository test 코드 추가
> [bugfix/#192] Entity 설정 오류 해결

- module-auth/src/main/java/com/inhabas/api/auth/domain/oauth2/member/service/MemberService.java
- module-auth/src/main/java/com/inhabas/api/auth/domain/oauth2/member/service/MemberServiceImpl.java
- resource-server/src/main/java/com/inhabas/api/domain/contest/repository/ContestBoardRepositoryImpl.java
- resource-server/src/main/java/com/inhabas/api/web/MemberController.java
- resource-server/src/test/java/com/inhabas/api/domain/signUp/usecase/AnswerServiceTest.java
- resource-server/src/test/java/com/inhabas/api/web/MemberControllerTest.java
제네릭 관련 문제가 대부분이었고 이미 구현이 안된 부분에서 발생하는 경고는 일단 무시하도록 처리를 했다.
> [refactor/#195] Warning 코드 수정

- .github/workflows/gradle-build.yml
Reverts InhaBas/Inhabas.com-api#202
> Revert "[bugfix/#201] github workflow 수정"

- resource-server/src/main/java/com/inhabas/api/domain/club/usecase/ClubHistoryServiceImpl.java
JPAQuery를 사용할까 생각했지만 오히려 코드가 복잡해질거라 판단하여 Sort로 간단하게 해결했다.
> [feature/#204] 연혁 조회 날짜 역순 정렬

- resource-server/src/main/java/com/inhabas/api/domain/normalBoard/dto/SaveNormalBoardDto.java
- resource-server/src/main/java/com/inhabas/api/web/NormalBoardController.java
- resource-server/src/test/java/com/inhabas/api/domain/contest/domain/ContestBoardTest.java
- resource-server/src/test/java/com/inhabas/api/domain/contest/usecase/ContestBoardServiceImplTest.java
- resource-server/src/test/java/com/inhabas/api/domain/menu/domain/valueObject/MenuGroupExampleTest.java
- resource-server/src/test/java/com/inhabas/api/domain/normalBoard/dto/NormalBoardDetailDtoTest.java
- resource-server/src/test/java/com/inhabas/api/domain/normalBoard/dto/NormalBoardDtoTest.java
- resource-server/src/test/java/com/inhabas/api/domain/normalBoard/dto/SaveNormalBoardDtoTest.java
- resource-server/src/test/java/com/inhabas/api/domain/normalBoard/usecase/NormalBoardServiceImplTest.java
- resource-server/src/test/java/com/inhabas/api/web/NormalBoardControllerTest.java
contestBoard, normalBoard requestPart 통합 및 리펙토링 및 테스트 코드 오류 해결
Postman CRUD 테스트 완료
> [Refactor/Inhabas#241] contestBoard, normalBoard @requestPart 수정

- resource-server/src/main/java/com/inhabas/api/domain/contest/domain/ContestBoard.java
- resource-server/src/main/java/com/inhabas/api/web/ContestBoardController.java
- resource-server/src/main/java/com/inhabas/api/web/NormalBoardController.java
변경사항
1. 공모전 게시판의 updateFiles 메서드 중복으로 인해 제거
2. 공모전 게시판, normal  게시판 API response 명세서와 통일
> [refactor/Inhabas#241] 공모전 게시판 중복 메서드 제거, 게시판 API response 명세서와 통일

- resource-server/src/main/java/com/inhabas/api/domain/budget/dto/BudgetApplicationRegisterForm.java
- resource-server/src/main/java/com/inhabas/api/domain/budget/dto/BudgetHistoryCreateForm.java
- resource-server/src/main/java/com/inhabas/api/domain/budget/usecase/BudgetApplicationService.java
- resource-server/src/main/java/com/inhabas/api/domain/budget/usecase/BudgetApplicationServiceImpl.java
- resource-server/src/main/java/com/inhabas/api/domain/budget/usecase/BudgetHistoryService.java
- resource-server/src/main/java/com/inhabas/api/domain/budget/usecase/BudgetHistoryServiceImpl.java
- resource-server/src/main/java/com/inhabas/api/web/BudgetApplicationController.java
- resource-server/src/main/java/com/inhabas/api/web/BudgetHistoryController.java
> [feature/#251] 첨부파일 개편으로 인한 budget 수정

- module-auth/src/main/java/com/inhabas/api/auth/domain/oauth2/member/domain/entity/UpdateNameRequest.java
- resource-server/src/main/java/com/inhabas/api/domain/member/usecase/MemberProfileServiceImpl.java
- resource-server/src/main/java/com/inhabas/api/web/MyInfoController.java
- resource-server/src/test/java/com/inhabas/api/domain/member/usecase/MemberProfileServiceImplTest.java
clean build, 스웨거로 정상적으로 작동하는지 확인 완료했습니다.
> [refactor/Inhabas#264] 이름 변경 승인 시 변경된 이름 적용

- resource-server/src/main/java/com/inhabas/api/domain/myInfo/dto/MyBoardDto.java
- resource-server/src/main/java/com/inhabas/api/domain/myInfo/dto/MyCommentDto.java
- resource-server/src/main/java/com/inhabas/api/domain/myInfo/repository/MyInfoRepositoryImpl.java
- resource-server/src/test/java/com/inhabas/api/domain/myInfo/domain/MyBoardExampleTest.java
- resource-server/src/test/java/com/inhabas/api/domain/myInfo/dto/MyBoardDtoTest.java
- resource-server/src/test/java/com/inhabas/api/domain/myInfo/dto/MyCommentDtoTest.java
- resource-server/src/test/java/com/inhabas/api/domain/myInfo/repository/MyInfoRepositoryTest.java
> [refactor/Inhabas#268] [내 정보]  내가 쓴 글, 댓글 조회 MenuType return에 추가 및 내가 쓴 게시글 조회에서 회계내역 표시되는 문제 해결

- resource-server/src/main/java/com/inhabas/api/domain/contest/domain/ContestBoard.java
- resource-server/src/main/java/com/inhabas/api/domain/contest/domain/valueObject/OrderBy.java
- resource-server/src/main/java/com/inhabas/api/domain/contest/dto/ContestBoardDto.java
- resource-server/src/main/java/com/inhabas/api/domain/contest/repository/ContestBoardRepositoryImpl.java
- resource-server/src/main/java/com/inhabas/api/web/ContestBoardController.java
- resource-server/src/main/java/com/inhabas/api/web/converter/ContestOrderByConverter.java
- resource-server/src/test/java/com/inhabas/api/domain/contest/dto/ContestBoardDtoTest.java
- resource-server/src/test/java/com/inhabas/api/domain/contest/repository/ContestBoardRepositoryTest.java
- resource-server/src/test/java/com/inhabas/api/domain/contest/usecase/ContestBoardServiceImplTest.java
- resource-server/src/test/java/com/inhabas/api/web/ContestBoardControllerTest.java
clean build 테스트 완료
swagger 공모전 게시판 정렬 테스트 완료
> [feature/Inhabas#295] 공모전 정렬기능 수정

- resource-server/src/main/java/com/inhabas/api/domain/club/dto/ClubActivityDetailDto.java
- resource-server/src/main/java/com/inhabas/api/domain/club/dto/ClubActivityDto.java
- resource-server/src/main/java/com/inhabas/api/domain/club/repository/ClubActivityRepository.java
- resource-server/src/main/java/com/inhabas/api/domain/club/repository/ClubActivityRepositoryCustom.java
- resource-server/src/main/java/com/inhabas/api/domain/club/repository/ClubActivityRepositoryImpl.java
- resource-server/src/main/java/com/inhabas/api/domain/club/usecase/ClubActivityService.java
- resource-server/src/main/java/com/inhabas/api/domain/club/usecase/ClubActivityServiceImpl.java
- resource-server/src/main/java/com/inhabas/api/domain/contest/usecase/ContestBoardServiceImpl.java
- resource-server/src/main/java/com/inhabas/api/web/ClubActivityController.java
- resource-server/src/test/java/com/inhabas/api/domain/club/dto/ClubActivityDetailDtoTest.java
- resource-server/src/test/java/com/inhabas/api/domain/club/dto/ClubActivityDtoTest.java
- resource-server/src/test/java/com/inhabas/api/domain/club/usecase/ClubActivityServiceImplTest.java
- resource-server/src/test/java/com/inhabas/api/web/ClubActivityControllerTest.java
clean build, swagger 테스트 진행 했습니다.
1. 동아리 활동 게시판 정렬기능 추가
2. 동아리 활동  게시판 writerId 추가
3. 동아리 활동 게시판 수정시 title, content 수정 안되는 문제 해결
> [feature/Inhabas#298] 동아리활동 게시글 수정시 text변경안되는 문제 해결 및 정렬 기능 추가

- gradlew
- module-auth/src/main/java/com/inhabas/api/auth/domain/oauth2/member/dto/UpdateNameRequestDto.java
- resource-server/src/main/java/com/inhabas/api/domain/budget/dto/BudgetApplicationDetailDto.java
- resource-server/src/main/java/com/inhabas/api/domain/budget/dto/BudgetApplicationDto.java
- resource-server/src/main/java/com/inhabas/api/domain/budget/dto/BudgetApplicationRegisterForm.java
- resource-server/src/main/java/com/inhabas/api/domain/budget/dto/BudgetHistoryCreateForm.java
- resource-server/src/main/java/com/inhabas/api/domain/budget/dto/BudgetHistoryDetailDto.java
- resource-server/src/main/java/com/inhabas/api/domain/budget/dto/BudgetHistoryDto.java
- resource-server/src/main/java/com/inhabas/api/domain/club/dto/ClubActivityDetailDto.java
- resource-server/src/main/java/com/inhabas/api/domain/club/dto/ClubActivityDto.java
- resource-server/src/main/java/com/inhabas/api/domain/comment/dto/CommentDetailDto.java
- resource-server/src/main/java/com/inhabas/api/domain/contest/dto/ContestBoardDetailDto.java
- resource-server/src/main/java/com/inhabas/api/domain/contest/dto/ContestBoardDto.java
- resource-server/src/main/java/com/inhabas/api/domain/contest/dto/SaveContestBoardDto.java
- resource-server/src/main/java/com/inhabas/api/domain/myInfo/dto/MyBudgetSupportApplicationDto.java
- resource-server/src/main/java/com/inhabas/api/domain/normalBoard/dto/NormalBoardDetailDto.java
- resource-server/src/main/java/com/inhabas/api/domain/normalBoard/dto/NormalBoardDto.java
- resource-server/src/main/java/com/inhabas/api/domain/project/dto/ProjectBoardDetailDto.java
- resource-server/src/main/java/com/inhabas/api/domain/project/dto/ProjectBoardDto.java
- resource-server/src/main/java/com/inhabas/api/domain/scholarship/dto/SaveScholarshipBoardDto.java
- resource-server/src/main/java/com/inhabas/api/domain/scholarship/dto/SaveScholarshipHistoryDto.java
- resource-server/src/main/java/com/inhabas/api/domain/scholarship/dto/ScholarshipBoardDetailDto.java
- resource-server/src/main/java/com/inhabas/api/domain/scholarship/dto/ScholarshipBoardDto.java
- resource-server/src/main/java/com/inhabas/api/domain/signUp/dto/ApplicationDetailDto.java
- resource-server/src/main/java/com/inhabas/api/domain/signUpSchedule/dto/SignUpScheduleDto.java
- resource-server/src/test/java/com/inhabas/api/domain/budget/repository/BudgetHistoryRepositoryTest.java
hotfix/#355 Schema 변경 및 일괄 수정, BudgetHistoryRepositoryTest 회계내역 있는 연도 2025년 추가
> hotfix/#355 Schema 변경 및 일괄 수정, BudgetHistoryRepositoryTest 회계내역 있는 연도 2025년 추가

- Dockerfile
openjdk:17-jre-slim -> eclipse-temurin:17-jre-jammy
Refs #350
> [fix/#350] 도커 베이스 이미지 수정
